FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CarServiceMate/CarServiceMate.csproj", "CarServiceMate/"]
RUN dotnet restore "CarServiceMate/CarServiceMate.csproj"
COPY . .
WORKDIR "/src/CarServiceMate"
RUN dotnet build "CarServiceMate.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CarServiceMate.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CarServiceMate.dll"]
